version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_xm
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: xm_data
      MYSQL_USER: xm_user
      MYSQL_PASSWORD: xm_password
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
